sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t arnosgh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arnosgh/docker-react npm run test